
export const CardData = [
    {
        images:'/images/product-1.jpg',
        title:"jgf",
        price:"16.64"
    },
    {
        images:'/images/product-2.jpg',
        title:"jgf",
        price:"16.64"
    },
    {
        images:'/images/product-3.jpg',
        title:"jgf",
        price:"16.64"
    },
    {
        images:'/images/product-4.jpg',
        title:"jgf",
        price:"16.64"
    },
    {
        images:'/images/product-5.jpg',
        title:"jgf",
        price:"16.64"
    },
    {
        images:'/images/product-6.jpg',
        title:"jgf",
        price:"16.64"
    },
    {
        images:'/images/product-7.jpg',
        title:"jgf",
        price:"16.64"
    },
    {
        images:'/images/product-8.jpg',
        title:"jgf",
        price:"16.64"
    },
    {
        images:'/images/product-9.jpg',
        title:"jgf",
        price:"16.64"
    },
    {
        images:'/images/product-10.jpg',
        title:"jgf",
        price:"16.64"
    },
    {
        images:'/images/product-11.jpg',
        title:"jgf",
        price:"16.64"
    },
    {
        images:'/images/product-12.jpg',
        title:"jgf",
        price:"16.64"
    },
    {
        images:'/images/product-13.jpg',
        title:"jgf",
        price:"16.64"
    },
    {
        images:'/images/product-14.jpg',
        title:"jgf",
        price:"16.64"
    },
    {
        images:'/images/product-15.jpg',
        title:"jgf",
        price:"16.64"
    },
    {
        images:'/images/product-16.jpg',
        title:"jgf",
        price:"16.64"
    },
    
]